name: Setup Javy
description: 🟨 Install Javy for GitHub Actions

branding:
  icon: play
  color: blue

inputs:
  javy-version:
    description: Which version of Javy to install. This can be an exact version specifier such as '1.3.0' or a semver range like '~1.3.0' or '1.x'. Use 'latest' to always install the latest release. Defaults to 'latest'.
    default: latest
  javy-token:
    description: The GitHub token to use when fetching the version list from bytecodealliance/javy. You shouldn't have to touch this. The default is the 'github.token' if you're on github.com or unauthenticated (rate limited) if you're not on github.com.
    default: ${{ github.server_url == 'https://github.com' && github.token || '' }}

outputs:
  javy-version:
    description: The version of Javy that was installed. This will be something like '1.3.0' or similar.
  cache-hit:
    description: Whether or not Javy was restored from the runner's cache or download anew.

runs:
  using: node20
  main: dist/main.js
